> Projeto Desenvolve <br>
Programação Intermediária com Python <br>
Profa. Camila Laranjeira (mila@projetodesenvolve.com.br) <br>

# 3.6 - Pandas

## Exercícios
Antes de continuar, baixe os arquivos das bases de dados de partidas em Copas do Mundo e salve na mesma pasta deste notebook.
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1930_2022.csv
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1991_2023.csv

A célula a seguir já carrega os dados em CSV e ajusta as colunas para trabalharmos com os nomes traduzidos (como fizemos em aula).

In [ ]:
import pandas as pd
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',12)

wcwomen_df = pd.read_csv('matches_1991_2023.csv')
wcmen_df   = pd.read_csv('matches_1930_2022.csv')
wc = pd.concat((wcwomen_df,wcmen_df)).reset_index()

nomes_traduzidos = {'home_team': 'time_1', 'away_team': 'time_2', 'home_score': 'gols_1', 'away_score': 'gols_2',
                    'Date': 'data', 'Year': 'ano', 'Host': 'país_sede', 'Attendance': 'comparecimento',
                    'Score': 'resultado', 'Round': 'rodada', 'home_goal': 'gols_1_detalhes', 'away_goal': 'gols_2_detalhes',
                    'home_own_goal': 'gols_1_contra', 'away_own_goal': 'gols_2_contra',
                    'home_penalty_goal': 'gols_1_penalti', 'away_penalty_goal': 'gols_2_penalti',
                    'home_red_card': 'cartao_vermelho_1', 'away_red_card': 'cartao_vermelho_2',
                    'home_yellow_card_long': 'cartao_amarelo_1', 'away_yellow_card_long': 'cartao_amarelo_2'}

wc = wc.loc[:, nomes_traduzidos.keys()]
wc.columns = nomes_traduzidos.values()

copa = wc['ano'].apply( lambda x: 'Masculina' if x % 2 == 0 else 'Feminina').astype('string')
wc['copa'] = copa
display(wc)

,time_1,time_2,gols_1,gols_2,data,ano,país_sede,comparecimento,resultado,rodada,gols_1_detalhes,gols_2_detalhes,gols_1_contra,gols_2_contra,gols_1_penalti,gols_2_penalti,cartao_vermelho_1,cartao_vermelho_2,cartao_amarelo_1,cartao_amarelo_2,copa
0,Spain,England,1,0,2023-08-20,2023,"Australia, New Zealand",75784,1–0,Final,Olga Carmona · 29’,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['78’|1:0|Salma Paralluelo'],['55’|1:0|Lauren Hemp'],Feminina
1,Sweden,Australia,2,0,2023-08-19,2023,"Australia, New Zealand",49461,2–0,Third-place match,Kosovare Asllani · 62’,NaN,NaN,NaN,Fridolina Rolfö (P) · 30’,NaN,NaN,NaN,"['88’|2:0|Elin Rubensson', '90+5’|2:0|Lina Hur...",['45+1’|1:0|Katrina Gorry'],Feminina
2,Australia,England,1,3,2023-08-16,2023,"Australia, New Zealand",75784,1–3,Semi-finals,Sam Kerr · 63’,Ella Toone · 36’|Lauren Hemp · 71’|Alessia Rus...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['10’|0:0|Alex Greenwood', '90+5’|1:3|Chloe Ke...",Feminina
3,Spain,Sweden,2,1,2023-08-15,2023,"Australia, New Zealand",43217,2–1,Semi-finals,Salma Paralluelo · 81’|Olga Carmona · 89’,Rebecka Blomqvist · 88’,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Feminina
4,Australia,France,0,0,2023-08-12,2023,"Australia, New Zealand",49461,(7) 0–0 (6),Quarter-finals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['92’|0:0|Katrina Gorry'],NaN,Feminina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,Argentina,France,1,0,1930-07-15,1930,Uruguay,23409,1–0,Group stage,Luis Monti · 81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1308,Yugoslavia,Brazil,2,1,1930-07-14,1930,Uruguay,24059,2–1,Group stage,Aleksandar Tirnanić · 21|Ivan Bek · 30,Preguinho · 62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1309,Romania,Peru,3,1,1930-07-14,1930,Uruguay,2549,3–1,Group stage,Adalbert Deșu · 1|Constantin Stanciu · 79|Nico...,Luis de Souza Ferreira · 75,NaN,NaN,NaN,NaN,NaN,Plácido Galindo · 70,NaN,NaN,Masculina
1310,United States,Belgium,3,0,1930-07-13,1930,Uruguay,18346,3–0,Group stage,Bart McGhee · 23|Tom Florie · 45|Bert Patenaud...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1311,France,Mexico,4,1,1930-07-13,1930,Uruguay,4444,4–1,Group stage,Lucien Laurent · 19|Marcel Langiller · 40|Andr...,Juan Carreño · 70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina

#### Q1.
Faça as conversões de tipo necessárias para que a saída do comando `wc.info()` seja como apresentado a seguir. E **salve o novo dataframe** com o comando `df.to_csv('wc_formatado.csv')`.

```
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   time_1             1312 non-null   string        
 1   time_2             1312 non-null   string        
 2   gols_1             1312 non-null   int64         
 3   gols_2             1312 non-null   int64         
 4   data               1312 non-null   datetime64[ns]
 5   ano                1312 non-null   int64         
 6   país_sede          1312 non-null   string        
 7   comparecimento     1312 non-null   int64         
 8   resultado          1312 non-null   string        
 9   rodada             1312 non-null   category      
 10  gols_1_detalhes    970 non-null    string        
 11  gols_2_detalhes    771 non-null    string        
 12  gols_1_contra      57 non-null     string        
 13  gols_2_contra      30 non-null     string        
 14  gols_1_penalti     170 non-null    string        
 15  gols_2_penalti     119 non-null    string        
 16  cartao_vermelho_1  59 non-null     string        
 17  cartao_vermelho_2  65 non-null     string        
 18  cartao_amarelo_1   834 non-null    string        
 19  cartao_amarelo_2   857 non-null    string        
 20  copa               1312 non-null   string
```

In [ ]:
wc['gols_1'] = wc['gols_1'].astype('int')
wc['gols_2'] = wc['gols_2'].astype('int')
wc['data'] = pd.to_datetime(wc['data'])
wc['comparecimento'] = wc['comparecimento'].astype('int')
wc['rodada'] = wc['rodada'].astype('category')
wc["time_1"] = wc["time_1"].astype("string")
wc["time_2"] = wc["time_2"].astype("string")
wc["país_sede"] = wc["país_sede"].astype("string")
wc["resultado"] = wc["resultado"].astype("string")
wc['rodada'] = wc['rodada'].astype('category')
wc['gols_1_detalhes'] = wc['gols_1_detalhes'].astype('string')
wc['gols_2_detalhes'] = wc['gols_2_detalhes'].astype('string')
wc['gols_1_contra'] = wc['gols_1_contra'].astype('string')
wc['gols_2_contra'] = wc['gols_2_contra'].astype('string')
wc['gols_1_penalti'] = wc['gols_1_penalti'].astype('string')
wc['gols_2_penalti'] = wc['gols_2_penalti'].astype('string')
wc['cartao_vermelho_1'] = wc['cartao_vermelho_1'].astype('string')
wc['cartao_vermelho_2'] = wc['cartao_vermelho_2'].astype('string')
wc['cartao_amarelo_1'] = wc['cartao_amarelo_1'].astype('string')
wc['cartao_amarelo_2'] = wc['cartao_amarelo_2'].astype('string')


wc.info()
wc.to_csv('wc_formatado.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time_1             1312 non-null   string
 1   time_2             1312 non-null   string
 2   gols_1             1312 non-null   int64
 3   gols_2             1312 non-null   int64
 4   data               1312 non-null   datetime64[ns]
 5   ano                1312 non-null   int64
 6   país_sede          1312 non-null   string
 7   comparecimento     1312 non-null   int64
 8   resultado          1312 non-null   string
 9   rodada             1312 non-null   category
 10  gols_1_detalhes    970 non-null    string
 11  gols_2_detalhes    771 non-null    string
 12  gols_1_contra      57 non-null     string
 13  gols_2_contra      30 non-null     string
 14  gols_1_penalti     170 non-null    string
 15  gols_2_penalti     119 non-null    string
 16  cartao_vermelho_1  59 non-null     string
 17  cartao_vermelho_2  65 non-null     string
 18  cartao_amarelo_1   834 non-null    string
 19  cartao_amarelo_2   857 non-null    string
 20  copa               1312 non-null   string
dtypes: category(1), datetime64[ns](1), int64(4), string(15)
memory usage: 206.8 KB

#### Q2.
Apresente a linha do dataframe `wc` que corresponde ao jogo com maior audiência da história.

In [ ]:
wc.loc[wc['comparecimento'] == wc['comparecimento'].max()]

,time_1,time_2,gols_1,gols_2,data,ano,país_sede,comparecimento,resultado,rodada,gols_1_detalhes,gols_2_detalhes,gols_1_contra,gols_2_contra,gols_1_penalti,gols_2_penalti,cartao_vermelho_1,cartao_vermelho_2,cartao_amarelo_1,cartao_amarelo_2,copa
1238,Uruguay,Brazil,2,1,1950-07-16,1950,Brazil,173850,2–1,Final stage,Juan Alberto Schiaffino · 66|Alcides Ghiggia · 79,Friaça · 47,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Masculina

#### Q3.
Aplicando operações sobre as colunas `ano` e `copa` do dataframe `wc`, apresente quantas copas femininas e quantas copas masculinas já aconteceram na história.

Exemplo de saída (valores inventados):
```
Masculina: 22
Feminina: 9
```

In [ ]:
n_masculinas = wc[wc['copa'] == 'Masculina']['ano'].nunique()
n_femininas = wc[wc['copa'] == 'Feminina']['ano'].nunique()
print(f'Numero de copas \nCopas do masculino: {n_masculinas}\nCopas do feminino: {n_femininas}')

Numero de copas
Copas do masculino: 22
Copas do feminino: 9

#### Q3.
Crie um dataframe `participacao` com as colunas `país`, `copa`, e `num_copas` que armazena a quantidade de copas do mundo que cada país participou, informando se é da copa masculina ou feminina. Ao final imprima, como apresentado a seguir, o top 5 países de cada competição que mais participou de copas do mundo.

Exemplo de saída (valores inventados):
```
país            copa        num_copas
Brazil          Feminina    8
Unites States   Feminina    8
Germany         Feminina    8
Japan           Feminina    7
Colombia        Feminina    7
```

```
país            copa        num_copas
Brazil          Masculina   21
Germany         Masculina   21
Argentina       Masculina   20
England         Masculina   20
Mexico          Masculina   20
```

In [ ]:
participacao = wc.groupby(['time_1', 'copa'])['ano'].nunique().reset_index()
participacao.columns = ['país', 'copa', 'num_copas']
participacao = participacao.sort_values(['copa', 'num_copas'], ascending=[True, False])


print(participacao[participacao['copa'] == 'Feminina'].head(5).to_string(index=False))
print(participacao[participacao['copa'] == 'Masculina'].head(5).to_string(index=False))

         país     copa  num_copas
       Brazil Feminina          9
      Germany Feminina          9
       Norway Feminina          9
       Sweden Feminina          9
United States Feminina          9
     país      copa  num_copas
   Brazil Masculina         21
    Italy Masculina         18
Argentina Masculina         17
  England Masculina         16
    Spain Masculina         16

#### Q4.
* Crie um dataframe `gols` com duas colunas `país` e `total_gols` com o total de gols marcados por cada país durante todas as copas do mundo, juntando gols em casa (`gols_1`) e gols como time visitante (`gols_2`).
* Imprima o dataframe `gols` ordenado de forma decrescente, para que os times com mais gols fiquem no topo.

Segue um exemplo ilustrativo com o formato do dataframe resultado:

```
país        total_gols
Brazil      120
Argentina   112
Germany     107
...
```

In [ ]:
gols_casa = wc.groupby('time_1')['gols_1'].sum().reset_index()
gols_fora = wc.groupby('time_2')['gols_2'].sum().reset_index()
gols_casa.columns = ['país', 'gols_casa']
gols_fora.columns = ['país', 'gols_fora']


#unindo as colunas dos países
gols = pd.merge(gols_casa, gols_fora, on='país', how='outer').fillna(0)
#soma dos gols casa e fora
gols['total_gols'] = gols['gols_casa'] + gols['gols_fora']

gols ['total_gols'] = gols['total_gols'].astype('int')
gols = gols[['país', 'total_gols']].sort_values('total_gols', ascending=False)
print (gols.head(5).to_string(index=False))

         país  total_gols
       Brazil         308
      Germany         254
United States         182
       France         180
       Sweden         165

#### Q5.
Qual país tomou mais cartões amarelos somando todas as copas?

Neste exercício você vai trabalhar com as colunas `cartao_amarelo_1` e `cartao_amarelo_2` onde cada observação é uma string represetando uma lista dos cartões amarelos de um único jogo na forma `minuto|placar|jogador(a)`. Por exemplo:
```
['16’|1:0|Rosana Gómez', '20’|2:0|Gabriela Chávez]
```

Recomendo criar colunas `num_cartoes_1` e `num_cartoes_2` a partir de cada coluna `cartao_amarelo_X` usando o método genérico `apply` para chamar uma função que você vai criar para transformar uma observação de cartão amarelo em uma contagem de elementos da lista.

Lembre de levar em consideração que muitas observações são `NaN`.

Em seguida faça sua mágica para agrupar as informações por país, acumular os cartões de jogos em casa e jogos visitante, e produzir o resultado final como apresentado a seguir (valores inventados):

```
país        cartões amarelos
Argentina   97
England     93
Australia   93
...
```

In [ ]:
import re


cartoes_casa = wc.groupby('time_1')['cartao_amarelo_1'].sum().reset_index()
cartoes_fora = wc.groupby('time_2')['cartao_amarelo_2'].sum().reset_index()
cartoes_casa.columns = ['país', 'cartao_amarelo_1']
cartoes_fora.columns = ['país', 'cartao_amarelo_2']

def contar_cartoes(texto):
    if pd.isnull(texto):
        return 0
    else:
        return len(re.findall(r"'(?:[^'\\]|\\.)*'", texto)) #define a separação dos cartões em['  ']


cartoes_casa['num_cartoes_1'] = cartoes_casa['cartao_amarelo_1'].apply(contar_cartoes)
cartoes_fora['num_cartoes_2'] = cartoes_fora['cartao_amarelo_2'].apply(contar_cartoes)

cartoes = pd.merge(cartoes_casa, cartoes_fora, on='país', how='outer')
cartoes['cartoes_amarelos'] = cartoes['num_cartoes_1'] + cartoes['num_cartoes_2']
cartoes = cartoes[['país', 'cartoes_amarelos']].sort_values('cartoes_amarelos', ascending=False).fillna(0)


cartoes['cartoes_amarelos'] = cartoes['cartoes_amarelos'].astype('int')
print(cartoes.head(5).to_string(index=False))

       país  cartoes_amarelos
     Brazil               168
  Argentina               162
    Germany               124
Netherlands               117
      Italy               106

#### Q6.
Qual o top10 jogadores com mais gols em copa? Considere gols em jogo e gols de pênalti.

Para conseguir essa informação, você precisará trabalhar com as colunas:
```
10  gols_1_detalhes         
11  gols_2_detalhes    
14  gols_1_penalti     
15  gols_2_penalti     
```

Essas também são colunas textuais, onde cada observações apresenta todos os gols de uma partida separados pelo caracter `|`. Cada gol está na forma `'Jogador(a) · minuto’'`. Por exemplo:
```
'Alex Morgan · 12’|Rose Lavelle · 20’'
```

Lembre de levar em consideração que muitas observações são `NaN`.

Recomendo criar um dicionário à parte, onde cada chave será um jogador encontrado nessas colunas do dataframe `wc` e o valor correspondente será a contagem de ocorrências desses nomes.

Em seguida basta converter o seu dicionário em um dataframe e imprimí-lo na forma (valores não são inventados 😁):
```
jogador(a)      num_gols
Marta           17
Miroslav Klose  16
...
```

In [ ]:
# Cria um novo DataFrame vazio
gols_detalhados_df = pd.DataFrame()

# Itera sobre as colunas relevantes do DataFrame wc
for coluna in ['gols_1_detalhes', 'gols_2_detalhes', 'gols_1_penalti', 'gols_2_penalti']:
    # Separa os gols em novas linhas e adiciona ao novo DataFrame
    gols_separados = wc[coluna].str.split('|', expand=True).stack().reset_index(level=1, drop=True).rename(coluna + '_separados')
    gols_detalhados_df = pd.concat([gols_detalhados_df, wc[['data', 'time_1', 'time_2', 'copa']].join(gols_separados)], axis=0)

# Remove as linhas com valores nulos na coluna 'gols_detalhes_separados'
gols_detalhados_df = gols_detalhados_df.dropna(subset=['gols_1_detalhes_separados', 'gols_2_detalhes_separados', 'gols_1_penalti_separados', 'gols_2_penalti_separados'], how='all')

def remover_apos_ponto(texto):
  if pd.isna(texto):
    return texto
  else:
    return texto.split('·')[0].strip()

# Aplica a função às colunas criadas
for coluna in ['gols_1_detalhes_separados', 'gols_2_detalhes_separados', 'gols_1_penalti_separados', 'gols_2_penalti_separados']:
    gols_detalhados_df[coluna] = gols_detalhados_df[coluna].apply(remover_apos_ponto)

display(gols_detalhados_df)

,data,time_1,time_2,copa,gols_1_detalhes_separados,gols_2_detalhes_separados,gols_1_penalti_separados,gols_2_penalti_separados
0,2023-08-20,Spain,England,Feminina,Olga Carmona,<NA>,<NA>,<NA>
1,2023-08-19,Sweden,Australia,Feminina,Kosovare Asllani,<NA>,<NA>,<NA>
2,2023-08-16,Australia,England,Feminina,Sam Kerr,<NA>,<NA>,<NA>
3,2023-08-15,Spain,Sweden,Feminina,Salma Paralluelo,<NA>,<NA>,<NA>
3,2023-08-15,Spain,Sweden,Feminina,Olga Carmona,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...
1265,1938-06-12,Brazil,Czechoslovakia,Masculina,<NA>,<NA>,<NA>,Oldřich Nejedlý (P)
1274,1938-06-05,Brazil,Poland,Masculina,<NA>,<NA>,<NA>,Friedrich Scherfke (P)
1282,1934-05-31,Austria,Hungary,Masculina,<NA>,<NA>,<NA>,György Sárosi (P)
1288,1934-05-27,Austria,France,Masculina,<NA>,<NA>,<NA>,Georges Verriest (P)
1302,1930-07-19,Argentina,Mexico,Masculina,<NA>,<NA>,<NA>,Manuel Rosas (P)

In [ ]:
# Cria o DataFrame 'artilharia' com as colunas desejadas
artilharia = gols_detalhados_df[['gols_1_detalhes_separados', 'gols_2_detalhes_separados', 'gols_1_penalti_separados', 'gols_2_penalti_separados']].copy()

# Junta as quatro colunas em uma única coluna, removendo valores NaN
artilharia['todos_gols'] = artilharia.stack().reset_index(drop=True) #stack junta as colunas, drop true remove os indices
artilharia = artilharia[['todos_gols']].dropna()  # Seleciona apenas a coluna 'todos_gols' e remove linhas com NaN

#display(artilharia)

In [ ]:
# Conta as ocorrências de cada nome e cria um novo DataFrame
contagem_gols = artilharia['todos_gols'].value_counts().reset_index()

# Renomeia as colunas para 'jogador(a)' e 'num_gols'
contagem_gols.columns = ['jogador(a)', 'num_gols']

# Exibe o DataFrame com a contagem de gols
display(contagem_gols)

           jogador(a)  num_gols
0    Jürgen Klinsmann        45
1         Rudi Völler        32
2        Birgit Prinz        31
3      Miroslav Klose        29
4             Sun Wen        27
..                ...       ...
719             Cacau         1
720     Lieke Martens         1
721    Alex Greenwood         1
722   Nichelle Prince         1
723  Dennis Rommedahl         1

[724 rows x 2 columns]

In [3]:
from rich import print
import pandas as pd

superhero = pd.DataFrame(
    {"person": {"name": "John Jones", "age":30,
"address":{"street": "123 Main St", "city": "Gotham",
"state":"NY", "zip_code": "12345"},
"superpowers":{"leaps_buildings":True,"factorizes_polynomials":False},
 "contacts":[{"type":"email","value":"john.jones@heroes.are.us"},
 {"type":"phone","value":"555-123-4567"}],
 "hobbies": ["reading","hiking","coding","crimefighting"],
 "family":{"spouse": {"name":"Griselda Jones", "age":28},
 "children":[{"name":"Bellatrix", "age":5, "name":"Draco", "age":8}]}
                         }}
)
print(superhero)

                                                        person
name                                                John Jones
age                                                         30
address      {'street': '123 Main St', 'city': 'Gotham', 's...
superpowers  {'leaps_buildings': True, 'factorizes_polynomi...
contacts     [{'type': 'email', 'value': 'john.jones@heroes...
hobbies               [reading, hiking, coding, crimefighting]
family       {'spouse': {'name': 'Griselda Jones', 'age': 2...